Repository thoth-station/janusgraph-thoth-config, pull requests merged in 2018-11, with the labels that each got.

#5 Introduce artifact in the graph database
  scripts/thoth_schema_definition.groovy
Labels: size/XS

#6 Rename index url to respect semantics
  scripts/thoth_schema_definition.groovy
Labels: size/XS

#7 Adjust property name to reflect semantics
  scripts/thoth_schema_definition.groovy
Labels: approved, size/XS

#8 this stuff could be used with an OSP instance....
  .coafile
  ansible/group_vars/gremlin_servers.yaml
  ansible/hosts
  ansible/provision.retry
  ansible/provision.yaml
  ansible/templates/thoth-gremlin-server.service.j2
Labels: size/M
