Repository thoth-station/janusgraph-thoth-config, pull requests merged in 2019-02, with the labels that each got.

#19 Introduce properties for software stack differentiation
  scripts/thoth_schema_definition.groovy
Labels: size/S

#17 Add solver related information into schema
  scripts/thoth_schema_definition.groovy
Labels: size/XS

#20 Distinguish different software stack types
  scripts/thoth_schema_definition.groovy
Labels: size/S

#18 Remove Ansible's retry file
  ansible/provision.retry
Labels: size/XS

#22 Adjust schema - use generated one from Goblinoid
  scripts/thoth_schema_definition.groovy
Labels: approved, size/L

#23 Introduce a way on how to run JanusGraph locally
  README-thoth.md
  README.rst
  ansible/provision.yaml
  build-local.sh
  run-local.sh
Labels: size/L

#13 index creation script
  ansible/group_vars/gremlin_servers.yaml
  ansible/provision.yaml
  conf/gremlin-server/thoth.properties
  conf/gremlin-server/thoth.yaml
  conf/remote-test-2.yaml
  scripts/graph_init.groovy
  scripts/indices/byCVE.groovy
  scripts/indices/byDebPackageVersion.groovy
  scripts/indices/byDependsOn.groovy
  scripts/indices/byEcosystemSolver.groovy
  scripts/indices/byEdge.groovy
  scripts/indices/byIsPartOf.groovy
  scripts/indices/byPackage.groovy
  scripts/indices/byPythonArtifact.groovy
  scripts/indices/byPythonPackageIndex.groovy
  scripts/indices/byPythonPackageVersion.groovy
  scripts/indices/byRPMPackageVersion.groovy
  scripts/indices/byRPMRequirement.groovy
  scripts/indices/byRequires.groovy
  scripts/indices/byRuntimeEnvironment.groovy
  scripts/indices/bySolved.groovy
  scripts/show_indices.groovy
  scripts/submit-reindex-jobs.groovy
  scripts/wait-for-indexes.groovy
Labels: size/XL

#24 Introduce a local entrypoint
  bin/local-entrypoint.sh
  build-local.sh
  run-local.sh
  scripts/thoth_schema_definition.groovy
  vars.sh
Labels: size/M

#26 Update schema based on the current models
  scripts/thoth_schema_definition.groovy
Labels: size/L

#29 Fix wrong path to janusgraph workdir
  vars.sh
Labels: size/XS

#28 Use Thoth's configuration of Gremlin server
  bin/thoth-gremlin-server.sh
Labels: size/XS

#27 The feature branch does not exist anymore
  ansible/provision.yaml
Labels: size/XS

#30 Enhanced local experience with a local JanusGraph instance
  .gitignore
  README.rst
  ansible/group_vars/gremlin_servers.yaml
  ansible/provision.yaml
  bin/init.sh
  bin/local-entrypoint.sh
  build-local.sh
  local.sh
  run-local.sh
  scripts/indexes.groovy.template
  scripts/init.groovy
  scripts/show_indices.groovy
  scripts/submit-reindex-jobs.groovy
  scripts/thoth_schema_definition.groovy
  scripts/wait-for-indexes.groovy
  vars.sh
Labels: size/L, size/XXL

#32 Remove type from byPythonPackageVersion index
  scripts/init.groovy
Labels: approved, size/XS

#33 Regenerate, add missing has_artifact
  scripts/init.groovy
Labels: size/XS
