Repository thoth-station/janusgraph-thoth-config, pull requests merged in 2019-03, with the labels that each got.

#35 Add index to be used during CVE checks
  scripts/indexes.groovy.template
Labels: approved, size/XS

#37 Fix format of rst
  README.rst
Labels: size/XS

#38 State troubleshooting for number of opened files
  README.rst
Labels: size/S

#40 Add missing findutils
  ansible/provision.yaml
Labels: size/XS

#39 Introduce by document id needed when syncing inspection documents
  local.sh
  scripts/indexes.groovy.template
  scripts/init.groovy
Labels: size/S

#42 Turn ram_size into float
  scripts/init.groovy
Labels: size/XS

#44 Create index for querying by hardware information
  scripts/indexes.groovy.template
  scripts/init.groovy
Labels: size/S

#45 Create index for buildtime environment queries
  scripts/indexes.groovy.template
  scripts/init.groovy
Labels: size/S

#46 Make runtime and buildtime names common
  scripts/indexes.groovy.template
  scripts/init.groovy
Labels: size/M

#48 State remote connection to an instance
  README.rst
Labels: size/M

#49 Increase limit for scriptEvaluationTimeout Ref: #47
  conf/gremlin-server/thoth.yaml
Labels: approved, size/XS

#50 Fix/provision
  ansible/group_vars/gremlin_servers.yaml
  ansible/hosts
  ansible/provision.yaml
Labels: approved, size/M
